version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 80:80
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306